# Generated by Django 4.0.3 on 2022-04-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rent',
            new_name='transaction',
        ),
    ]
